import os
class Config:
	DEBUG = os.getenv('DEBUG')
	SECRET_KEY = os.getenv('SECRET_KEY')
	SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
	SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS')
	FRONTEND_URL = os.getenv('FRONTEND_URL')
	SES_ACCESS_KEY_ID = os.getenv('SES_ACCESS_KEY_ID')
	SES_SECRET_ACCESS_KEY = os.getenv('SES_SECRET_ACCESS_KEY')
	SES_SENDER_EMAIL = os.getenv('SES_SENDER_EMAIL')