import os
class Config:
	DEBUG = os.environ.get('DEBUG')
	SECRET_KEY = os.environ.get('SECRET_KEY')
	SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
	SQLALCHEMY_TRACK_MODIFICATIONS = os.environ.get('SQLALCHEMY_TRACK_MODIFICATIONS')
	FRONTEND_URL = os.environ.get('FRONTEND_URL')
	SES_ACCESS_KEY_ID = os.environ.get('SES_ACCESS_KEY_ID')
	SES_SECRET_ACCESS_KEY = os.environ.get('SES_SECRET_ACCESS_KEY')
	SES_SENDER_EMAIL = os.environ.get('SES_SENDER_EMAIL')