"""empty message

Revision ID: 89845d5134db
Revises: 
Create Date: 2023-05-26 21:10:27.631069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89845d5134db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dob')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
